kind: project
metadata:
  name: gitops-project
spec:
  functions: []
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/igz-us-sales/mlrun-github-actions-demo.git#refs/heads/master
  origin_url: git://github.com/igz-us-sales/mlrun-github-actions-demo.git#refs/heads/master
  desired_state: online
