kind: project
metadata:
  name: gitops-project
spec:
  functions:
  - url: components/gen_iris.py
    name: gen-iris
    kind: job
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: hub://describe
    name: describe
    kind: job
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: components/sklearn_classifier.py
    name: train
    kind: job
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: components/test_classifier.py
    name: test
    kind: job
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: hub://v2_model_server
    name: serving
    kind: serving
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: components/model_server_tester.py
    name: live-tester
    kind: nuclio
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  - url: components/drift_watcher.py
    name: drift-watcher
    kind: nuclio
    image: docker-registry.default-tenant.app.us-sales-eks.iguazio-cd0.com:80/gitops-image
  workflows:
  - name: train
    path: pipelines/train.py
  - name: deploy
    path: pipelines/deploy.py
  artifacts: []
  artifact_path: v3io:///users/{{run.user}}/pipe/{{workflow.uid}}
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
