kind: project
metadata:
  name: gitops-project-1
  created: '2023-06-29T22:39:23.851833'
spec:
  functions:
  - url: components/gen_iris.py
    name: gen-iris
    kind: job
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: hub://describe
    name: describe
    kind: job
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: components/train.py
    name: train
    kind: job
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: components/test_classifier.py
    name: test
    kind: job
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: hub://v2_model_server
    name: serving
    kind: serving
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: components/model_server_tester.py
    name: live-tester
    kind: nuclio
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  - url: components/drift_watcher.py
    name: drift-watcher
    kind: nuclio
    image: docker-registry.default-tenant.app.cst-353.iguazio-cd1.com/gitops-image:latest
  workflows:
  - path: pipelines/train.py
    name: train
  - path: pipelines/deploy.py
    name: deploy
  artifacts: []
  conda: ''
  source: git://github.com/igz-us-sales/mlrun-github-actions-demo.git#refs/heads/master
  origin_url: git://github.com/igz-us-sales/mlrun-github-actions-demo.git#refs/heads/master
  desired_state: online
  owner: xingsheng
status:
  state: online
