name: training-workflow
on: 
  workflow_dispatch:
    inputs:
      existing_model_path:
        description: 'Model path of existing model for comparison'     
        required: false
        default: 'None'

jobs:
  drift-dected:
    name: drift-trigged
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
    - name: echo github.event.comment.body
      run: echo ${{github.event.comment.body}}    

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: echo out github.event.issue.number
      run: echo ${{github.event.issue.number}} 
    - name: Model drift trigger re-training
      run: echo do nothing, just kick off the apprval process for re-training

      env:
        V3IO_USERNAME: ${{ secrets.V3IO_USERNAME }}
        V3IO_PASSWORD: ${{ secrets.V3IO_USERNAME }}
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CMD: ${{ github.event.comment.body}}  
        COMMIT: ${{ github.sha}}

  training-workflow:
    name: training-model
    runs-on: ubuntu-latest
    environment: 'qa'
    needs: [drift-dected]
    steps:
    - name: echo github.event.comment.body
      run: echo ${{github.event.comment.body}}    

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: echo out github.event.issue.number
      run: echo ${{github.event.issue.number}}    
    - name: Install mlrun
      run: python -m pip install mlrun==1.3.3
    - name: Training model

      run: |
        python -m mlrun project ./ --run train \
        --secrets env=MY_GITHUB_TOKEN \
        --git-repo ${GITHUB_REPOSITORY} \
        --git-issue 1 \
        -w -x commit=${COMMIT:33} \
        -a existing_model_path=${{ github.event.inputs.existing_model_path}} \
        -a force_deploy=true
      env:
        V3IO_USERNAME: ${{ secrets.V3IO_USERNAME }}
        V3IO_PASSWORD: ${{ secrets.V3IO_USERNAME }}
        V3IO_API: ${{ secrets.V3IO_API }}
        V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
        MLRUN_DBPATH: ${{ secrets.MLRUN_DBPATH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CMD: ${{ github.event.comment.body}}  
        COMMIT: ${{ github.sha}}
